version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'awakeseller'
      MYSQL_USER: 'awakeseller'
      MYSQL_PASSWORD: 'awakeseller'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - awakeseller-db:/var/lib/mysql
volumes:
  awakeseller-db: